# Generated by Django 4.2.4 on 2023-09-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'verbose_name': 'ModelName', 'verbose_name_plural': 'ModelNames'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='ModelName1',
        ),
    ]
