# Generated by Django 4.2.4 on 2023-09-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_article_options_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'ModelNames'},
        ),
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
